// <auto-generated />
namespace Blazing_Shop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addingproducts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingproducts));
        
        string IMigrationMetadata.Id
        {
            get { return "202010111424243_adding products"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
