// <auto-generated />
namespace Blazing_Shop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addAppointment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addAppointment));
        
        string IMigrationMetadata.Id
        {
            get { return "202010120248337_add Appointment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
